/* empty css                      */import{S as l,A as c}from"./assets/vendor-16iyBIrI.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();new l(".my-swiper",{modules:[c],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1.1,spaceBetween:16,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1},breakpoints:{1440:{slidesPerView:3,spaceBetween:32}}});document.querySelectorAll(".faq-acc-el-trigger").forEach(i=>{i.addEventListener("click",()=>{const s=i.closest(".faq-acc-el"),o=s.querySelector(".faq-acc-el-descr-frame"),r=i.querySelector("svg"),e=s.classList.contains("open"),t=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M14 6V22" stroke="#2B1F0E" stroke-width="2" stroke-linecap="round" />
  <path d="M22 14L6 14" stroke="#2B1F0E" stroke-width="2" stroke-linecap="round" />
</svg>`,n=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M22 14L6 14" stroke="#2B1F0E" stroke-width="2" stroke-linecap="round" />
</svg>`;e?(s.classList.remove("open"),o.style.maxHeight="0",r.outerHTML=t):(s.classList.add("open"),o.style.maxHeight=o.scrollHeight+"px",r.outerHTML=n)})});
//# sourceMappingURL=index.js.map
